// <auto-generated />
namespace _24HourChallenge.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatepost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepost));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230129383_update post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
